/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SignInRouteImport } from './pages/sign-in'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as AuthenticatedExploreRouteImport } from './pages/_authenticated/explore'
import { Route as AuthenticatedfeedLayoutRouteImport } from './pages/_authenticated/(feed)/layout'
import { Route as AuthenticatedUserIdLayoutRouteImport } from './pages/_authenticated/$userId/layout'
import { Route as AuthenticatedfeedIndexRouteImport } from './pages/_authenticated/(feed)/index'
import { Route as AuthenticatedfeedFollowingRouteImport } from './pages/_authenticated/(feed)/following'
import { Route as AuthenticatedUserIdFollowingRouteImport } from './pages/_authenticated/$userId/following'
import { Route as AuthenticatedUserIdFollowersRouteImport } from './pages/_authenticated/$userId/followers'
import { Route as AuthenticatedUserIdprofileLayoutRouteImport } from './pages/_authenticated/$userId/(profile)/layout'
import { Route as AuthenticatedUserIdprofileIndexRouteImport } from './pages/_authenticated/$userId/(profile)/index'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedfeedLayoutRoute = AuthenticatedfeedLayoutRouteImport.update({
  id: '/(feed)',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserIdLayoutRoute =
  AuthenticatedUserIdLayoutRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedfeedIndexRoute = AuthenticatedfeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedfeedLayoutRoute,
} as any)
const AuthenticatedfeedFollowingRoute =
  AuthenticatedfeedFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => AuthenticatedfeedLayoutRoute,
  } as any)
const AuthenticatedUserIdFollowingRoute =
  AuthenticatedUserIdFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => AuthenticatedUserIdLayoutRoute,
  } as any)
const AuthenticatedUserIdFollowersRoute =
  AuthenticatedUserIdFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => AuthenticatedUserIdLayoutRoute,
  } as any)
const AuthenticatedUserIdprofileLayoutRoute =
  AuthenticatedUserIdprofileLayoutRouteImport.update({
    id: '/(profile)',
    getParentRoute: () => AuthenticatedUserIdLayoutRoute,
  } as any)
const AuthenticatedUserIdprofileIndexRoute =
  AuthenticatedUserIdprofileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUserIdprofileLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedfeedIndexRoute
  '/sign-in': typeof SignInRoute
  '/$userId': typeof AuthenticatedUserIdprofileLayoutRouteWithChildren
  '/explore': typeof AuthenticatedExploreRoute
  '/$userId/followers': typeof AuthenticatedUserIdFollowersRoute
  '/$userId/following': typeof AuthenticatedUserIdFollowingRoute
  '/following': typeof AuthenticatedfeedFollowingRoute
  '/$userId/': typeof AuthenticatedUserIdprofileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedfeedIndexRoute
  '/sign-in': typeof SignInRoute
  '/$userId': typeof AuthenticatedUserIdprofileIndexRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/$userId/followers': typeof AuthenticatedUserIdFollowersRoute
  '/$userId/following': typeof AuthenticatedUserIdFollowingRoute
  '/following': typeof AuthenticatedfeedFollowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/$userId': typeof AuthenticatedUserIdLayoutRouteWithChildren
  '/_authenticated/(feed)': typeof AuthenticatedfeedLayoutRouteWithChildren
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/$userId/(profile)': typeof AuthenticatedUserIdprofileLayoutRouteWithChildren
  '/_authenticated/$userId/followers': typeof AuthenticatedUserIdFollowersRoute
  '/_authenticated/$userId/following': typeof AuthenticatedUserIdFollowingRoute
  '/_authenticated/(feed)/following': typeof AuthenticatedfeedFollowingRoute
  '/_authenticated/(feed)/': typeof AuthenticatedfeedIndexRoute
  '/_authenticated/$userId/(profile)/': typeof AuthenticatedUserIdprofileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/$userId'
    | '/explore'
    | '/$userId/followers'
    | '/$userId/following'
    | '/following'
    | '/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/$userId'
    | '/explore'
    | '/$userId/followers'
    | '/$userId/following'
    | '/following'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/$userId'
    | '/_authenticated/(feed)'
    | '/_authenticated/explore'
    | '/_authenticated/$userId/(profile)'
    | '/_authenticated/$userId/followers'
    | '/_authenticated/$userId/following'
    | '/_authenticated/(feed)/following'
    | '/_authenticated/(feed)/'
    | '/_authenticated/$userId/(profile)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(feed)': {
      id: '/_authenticated/(feed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedfeedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$userId': {
      id: '/_authenticated/$userId'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof AuthenticatedUserIdLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/(feed)/': {
      id: '/_authenticated/(feed)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedfeedIndexRouteImport
      parentRoute: typeof AuthenticatedfeedLayoutRoute
    }
    '/_authenticated/(feed)/following': {
      id: '/_authenticated/(feed)/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof AuthenticatedfeedFollowingRouteImport
      parentRoute: typeof AuthenticatedfeedLayoutRoute
    }
    '/_authenticated/$userId/following': {
      id: '/_authenticated/$userId/following'
      path: '/following'
      fullPath: '/$userId/following'
      preLoaderRoute: typeof AuthenticatedUserIdFollowingRouteImport
      parentRoute: typeof AuthenticatedUserIdLayoutRoute
    }
    '/_authenticated/$userId/followers': {
      id: '/_authenticated/$userId/followers'
      path: '/followers'
      fullPath: '/$userId/followers'
      preLoaderRoute: typeof AuthenticatedUserIdFollowersRouteImport
      parentRoute: typeof AuthenticatedUserIdLayoutRoute
    }
    '/_authenticated/$userId/(profile)': {
      id: '/_authenticated/$userId/(profile)'
      path: ''
      fullPath: '/$userId'
      preLoaderRoute: typeof AuthenticatedUserIdprofileLayoutRouteImport
      parentRoute: typeof AuthenticatedUserIdLayoutRoute
    }
    '/_authenticated/$userId/(profile)/': {
      id: '/_authenticated/$userId/(profile)/'
      path: '/'
      fullPath: '/$userId/'
      preLoaderRoute: typeof AuthenticatedUserIdprofileIndexRouteImport
      parentRoute: typeof AuthenticatedUserIdprofileLayoutRoute
    }
  }
}

interface AuthenticatedUserIdprofileLayoutRouteChildren {
  AuthenticatedUserIdprofileIndexRoute: typeof AuthenticatedUserIdprofileIndexRoute
}

const AuthenticatedUserIdprofileLayoutRouteChildren: AuthenticatedUserIdprofileLayoutRouteChildren =
  {
    AuthenticatedUserIdprofileIndexRoute: AuthenticatedUserIdprofileIndexRoute,
  }

const AuthenticatedUserIdprofileLayoutRouteWithChildren =
  AuthenticatedUserIdprofileLayoutRoute._addFileChildren(
    AuthenticatedUserIdprofileLayoutRouteChildren,
  )

interface AuthenticatedUserIdLayoutRouteChildren {
  AuthenticatedUserIdprofileLayoutRoute: typeof AuthenticatedUserIdprofileLayoutRouteWithChildren
  AuthenticatedUserIdFollowersRoute: typeof AuthenticatedUserIdFollowersRoute
  AuthenticatedUserIdFollowingRoute: typeof AuthenticatedUserIdFollowingRoute
}

const AuthenticatedUserIdLayoutRouteChildren: AuthenticatedUserIdLayoutRouteChildren =
  {
    AuthenticatedUserIdprofileLayoutRoute:
      AuthenticatedUserIdprofileLayoutRouteWithChildren,
    AuthenticatedUserIdFollowersRoute: AuthenticatedUserIdFollowersRoute,
    AuthenticatedUserIdFollowingRoute: AuthenticatedUserIdFollowingRoute,
  }

const AuthenticatedUserIdLayoutRouteWithChildren =
  AuthenticatedUserIdLayoutRoute._addFileChildren(
    AuthenticatedUserIdLayoutRouteChildren,
  )

interface AuthenticatedfeedLayoutRouteChildren {
  AuthenticatedfeedFollowingRoute: typeof AuthenticatedfeedFollowingRoute
  AuthenticatedfeedIndexRoute: typeof AuthenticatedfeedIndexRoute
}

const AuthenticatedfeedLayoutRouteChildren: AuthenticatedfeedLayoutRouteChildren =
  {
    AuthenticatedfeedFollowingRoute: AuthenticatedfeedFollowingRoute,
    AuthenticatedfeedIndexRoute: AuthenticatedfeedIndexRoute,
  }

const AuthenticatedfeedLayoutRouteWithChildren =
  AuthenticatedfeedLayoutRoute._addFileChildren(
    AuthenticatedfeedLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedUserIdLayoutRoute: typeof AuthenticatedUserIdLayoutRouteWithChildren
  AuthenticatedfeedLayoutRoute: typeof AuthenticatedfeedLayoutRouteWithChildren
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUserIdLayoutRoute: AuthenticatedUserIdLayoutRouteWithChildren,
  AuthenticatedfeedLayoutRoute: AuthenticatedfeedLayoutRouteWithChildren,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
